# Generated by Django 3.1.6 on 2021-02-26 15:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210211_2248'),
    ]

    operations = [
        migrations.CreateModel(
            name='Polls',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField()),
                ('choice1', models.CharField(max_length=50)),
                ('choice2', models.CharField(max_length=50)),
                ('choice3', models.CharField(blank=True, max_length=50)),
                ('choice4', models.CharField(blank=True, max_length=50)),
                ('choice5', models.CharField(blank=True, max_length=50)),
                ('choice1_total', models.IntegerField(default=0)),
                ('choice2_total', models.IntegerField(default=0)),
                ('choice3_total', models.IntegerField(default=0)),
                ('choice4_total', models.IntegerField(default=0)),
                ('choice5_total', models.IntegerField(default=0)),
                ('completed', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
            ],
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.polls')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.userprofile')),
            ],
            options={
                'unique_together': {('user', 'poll')},
                'index_together': {('user', 'poll')},
            },
        ),
    ]
