# Generated by Django 3.1.6 on 2021-03-04 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_polls_pollvote'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='justaskai',
            field=models.BooleanField(default=False),
        ),
    ]
