# Generated by Django 3.1.6 on 2021-03-04 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_posts_justaskai'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='justaskai',
        ),
    ]
